### PR TITLE
Optional required stop count

### PR DESCRIPTION
**Pull request by AnthonyDest**

### CODE REVIEW

**Review by JPCasasanta — APPROVED** [review]

**Comment by JPCasasanta** [comment]
the only thing i see is it pulls random bars, and if your number requested is equal to node length, it may take a long time to find all the bars

**Comment by AnthonyDest** [comment]
> the only thing i see is it pulls random bars, and if your number requested is equal to node length, it may take a long time to find all the bars

Can you please clarify this comment. The function is the same as before, with an optional parameter to specify a number of bars to create in the crawl, then it saturates the chosen number to ensure it’s within range.

**Comment by JPCasasanta** [comment]
> > the only thing i see is it pulls random bars, and if your number requested is equal to node length, it may take a long time to find all the bars
> 
> Can you please clarify this comment. The function is the same as before, with an optional parameter to specify a number of bars to create in the crawl, then it saturates the chosen number to ensure it’s within range.

just if your crawl has 15 stops, and your node list also has 15 bars, its trying to randomly choose 15 unique nodes from a list of 15 nodes, so it may take a while to find them all

**Review by Ryam-20151-2 — APPROVED** [review]

**Comment by AnthonyDest** [comment]
Yeah ideally we don't have a super big crawl, but it allows us to specify a qty so we can easily test crawls of a specific length

**Pull request merged**
